###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = '<a href="https://nocomplexity.com/">Maikel Mardjan (nocomplexity.com)</a>'
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['nocxstyle.css']
html_favicon = ''
html_last_updated_fmt = ''
html_logo = 'images/nocxbanner.png'
html_show_copyright = False
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'repository_url': 'https://github.com/nocomplexity/simplifypython', 'repository_branch': 'master', 'use_repository_button': True, 'use_edit_page_button': True, 'use_issues_button': True, 'logo': {'text': '<b>Simplify Python</b>'}, 'extra_footer': '<p><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a> <i>(c)Copyright 2018-2025, BM-Support.org - Maikel Mardjan. This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</i></a>.</p>'}
html_title = 'Simplify Python Coding'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'auto'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True

project = 'Simplify Python'
author = 'Maikel Mardjan'
version = 'Edition 2025-Q1'

simplepdf_file_name = "SimplifyPython.pdf"

simplepdf_vars = {
    'primary': '#FF0000',
    'secondary': '#379683',
    'cover': '#FF0000',
    'white': '#ffffff',
    'links': 'FF0000',     
    'cover-bg': 'url(simplifyPython.webp) no-repeat center', 
    'cover-overlay': 'rgba(211, 211, 211, 0.5)',       
    'top-left-content': 'counter(page)',
    'bottom-center-content': '"Simplify IT-> NO|Complexity "',
}

html_context = {
    'docs_scope': 'external',
    #'cover_logo_title': 'Simplify Security GUIDE',
    'cover_meta_data': 'NO|Complexity',
   }
